# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  build:
    
    env: 
        ADMIN: ${{ secrets.ADMIN }}
        CLIENTID: ${{ secrets.CLIENTID }}
        CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
        EMAILAPI: ${{ secrets.EMAILAPI }}
        FORGOT_PASS_TEMPLATE: ${{ secrets.FORGOT_PASS_TEMPLATE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        REG_AUTH_TEMPLATE: ${{ secrets.REG_AUTH_TEMPLATE }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm run detached
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: app-deployment
      url: "https://poojan-patel.github.io/codeforces-app/"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to App Deployment
        id: deployment
        uses: actions/deploy-pages@v1
